# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pingredients' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Pingredients
pod “PinterestSDK”, :git => “git@github.com:pinterest/ios-pdk.git”
  target 'Pingredients-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PingredientsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'Firebase/Core'
